export {BannerSection} from "./banner-section";
export {CategoriesSection} from "./categories-section";
export {InfoSection} from "./info-section";
export {MostRecentSection} from "./most-recent-section";
export {MostSoldSection} from "./most-sold-section";
export {RecommendSection} from "./recommend-section";
export {GoToProductsSection} from "./go-to-products-section";
export {DiscountSection} from './discount-section';
export {GoToCatalogSection} from './go-to-catalog-section';
